# Hyprpaper 配置文件 - 由随机脚本生成
preload = /home/baocj/.config/hypr/wallpapers/15.png
wallpaper {
        monitor = HDMI-A-1
        path = /home/baocj/.config/hypr/wallpapers/15.png
        fit_mode = cover
    }
    splash = false
