general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
#   path =$HOME/.config/hypr/wallpapers/4.jpg
	path =$HOME/.config/wpaperd/wallpapers/4.jpg
    color = rgba(25, 20, 20, 1.0)
}

label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = rgba(160, 136, 200, 1.0)
    font_size = 90
    font_family = Maple Mono		# JetBrainsMono Nerd Font Bold  

    
    position = -30, 0
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = rgba(160, 136, 200, 1.0)
    font_size = 25
    font_family = Maple Mono		# JetBrainsMono Nerd Font Bold  
  
    position = -30, -150
    halign = right
    valign = top
}

image {
    monitor =
#   path = $HOME/Desktop/x4.png
    path = $HOME/.config/hypr/x4.png
    size = 100
    rounding = -1 # negative values mean circle
    border_size = 4
    border_color = rgb(221, 221, 221)

    position = 0,160
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = false
    placeholder_text = 🤗 	# 默认显示
    hide_input = false
    rounding = -1 			# -1 means complete rounding (circle/oval)
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34) 	# 认证失败时显示状态
    fail_text = <i>$密码错误 <b>($ATTEMPTS)</b></i>
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
    invert_numlock = false # change color if numlock is off
    swap_font_color = false # see below

    position = 0, 80
    halign = center
    valign = bottom
}





